name: CI

on:
  push:
    branches:
    - main
  pull_request:
    paths-ignore:
    - README.md
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

permissions: {}

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.10'
        - '3.14'
        install-args:
        - ''
        - --extra HDF5

        include:
        - os: ubuntu-22.04
          python-version: '3.10'
          install-args: --extra HDF5 --resolution=lowest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        prune-cache: false

    - name: run tests
      run: |
        uv run --group test ${{ matrix.install-args }} \
          pytest --color=yes ${{ contains( matrix.install-args , 'lowest' ) && '-Wdefault' || '' }}


  type-check:
    runs-on: ubuntu-latest
    name: type check

    strategy:
      matrix:
        python-version:
        - '3.10'
        - '3.14'

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        prune-cache: false

    - name: Typecheck
      run: |
        uv run --frozen --group typecheck mypy src
