name: CI

on:
  push:
    branches:
    - main
  pull_request:
    paths-ignore:
    - README.md
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

permissions: {}

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.10'
        - '3.14'
        install-args:
        - ''
        - --extra HDF5

        include:
        - os: ubuntu-22.04
          python-version: '3.10'
          install-args: --extra HDF5 --resolution=lowest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: run tests
      run: |
        uv run --group test ${{ matrix.install-args }} \
          pytest --color=yes ${{ contains( matrix.install-args , 'lowest' ) && '-Wdefault' || '' }}


  type-check:
    runs-on: ubuntu-latest
    name: type check

    strategy:
      matrix:
        python-version:
        - '3.10'
        - '3.14'

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Typecheck
      run: |
        uv run --frozen --group typecheck mypy src
